### ISSUE TITLE
Problems installing on mac

### ISSUE THREAD

**Issue by Arvendui** [docbrown1955/marty-public#22]
Hi, I am trying to install following https://marty.in2p3.fr/download.html
Running source setup.sh /usr/local went smoothly, by when afterward running make I get the following error that I'm missing the library `Qt5PrintSupport_debug`. Googling it I could not find any indications on how to solve this issue. Thanks a lot for any suggestion!

`ld: library not found for -lQt5PrintSupport_debug
collect2: error: ld returned 1 exit status
make[3]: *** [grafed-gui.app/Contents/MacOS/grafed-gui] Error 1
make[2]: *** [grafed] Error 2
make[1]: *** [grafed] Error 2
make: *** [all] Error 2`

**Comment by docbrown1955** [comment]
Hi,

I recently changed the build procedure on the dev version. You can instead
download MARTY using

git clone https://github.com/docbrown1955/marty-public.git

And follow the instructions in the README.md file (or on the page
https://github.com/docbrown1955/marty-public). The dependencies that are
required are specified, you will need to install them before building MARTY
(that was the issue you had).
Tell me if you have any trouble, I am trying to maintain the support for
Mac but I do not have any machine to make tests so I need user feedback. I
would be glad that we work this out together so that I can adapt the
instructions for future MacOS users if you encounter any trouble with the
new building procedure :)

Best,
Gregoire

**Comment by Arvendui** [comment]
Hi, thanks for the feedback. My first attempt was in fact by cloning the repository. To me this is even more problematic because the default path to c and c++ are `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/`, and running `export` with an appropriate path does not work:
Running
`export CXX=/usr/bin/g++-10;export CC=/usr/bin/gcc-10;export FC=/usr/bin/gfortran-10;rm CMakeCache.txt ;cmake ..` yields
<img width="906" alt="Schermata 2022-06-21 alle 13 30 27" src="https://user-images.githubusercontent.com/65656894/174789216-29970eb6-8767-4ebf-9af7-18ce7b5d96f1.png">

**Comment by docbrown1955** [comment]
I see your `gfortran` is in `/usr/local/bin`, not in `/usr/bin`. Can you check there are actually `g++` and `gcc` in `/usr/bin` ? One reason for `cmake` to not use the provided compilers is if they do not actually exist.

**Comment by Arvendui** [comment]
You are right, gofortran is not in `/usr/bin/`, but it also seems that homebrew does not allow me to install to that directory...

**Comment by docbrown1955** [comment]
If all your compilers are in `/usr/local/bin` just change the `export` commands:
``` bash
export CXX=/usr/local/bin/g++
export CC=/usr/local/bin/gcc
export FC=/usr/local/bin/gfortran
```

**Comment by Arvendui** [comment]
Sorry for keep writing, but even with `export` with the filepaths as in my screen above I get exactly the same error

**Comment by docbrown1955** [comment]
Could you paste the result of the following command ?
``` bash
ls /usr/local/bin/gcc* usr/local/bin/g++* usr/local/bin/gfortran*
```

**Comment by docbrown1955** [comment]
Ok there is no bare `gcc` or `g++`. Then simply use 
``` bash
export CXX=/usr/local/bin/g++-11
export CC=/usr/local/bin/gcc-11
export FC=/usr/local/bin/gfortran-11
```
It should work

**Comment by docbrown1955** [comment]
Did you remove the `CMakeCache.txt` file ? In case of doubt, just delete the `build/` directory and start over.

**Comment by Arvendui** [comment]
> Did you remove the `CMakeCache.txt` file ? In case of doubt, just delete the `build/` directory and start over.

I did removed the cache every time but apparently it was not enough, by deleting the build dir a creating it again I got
<img width="567" alt="Schermata 2022-06-21 alle 14 17 36" src="https://user-images.githubusercontent.com/65656894/174797082-d272ca59-3bd1-422e-b8b7-ff252b73de1a.png">

**Comment by docbrown1955** [comment]
Ok now compilers are found. Could you open a new issue with this error ? It will help me and future MacOS users to separate the different issues :)
