### ISSUE TITLE
Could not find CONVERT using the following names: convert

### ISSUE THREAD

**Issue by Arvendui** [docbrown1955/marty-public#24]
> Did you remove the `CMakeCache.txt` file ? In case of doubt, just delete the `build/` directory and start over.

I did removed the cache every time but apparently it was not enough, by deleting the build dir a creating it again I got
<img width="567" alt="Schermata 2022-06-21 alle 14 17 36" src="https://user-images.githubusercontent.com/65656894/174797082-d272ca59-3bd1-422e-b8b7-ff252b73de1a.png">

_Originally posted by @Arvendui in https://github.com/docbrown1955/marty-public/issues/22#issuecomment-1161671337_

**Comment by docbrown1955** [comment]
Thank you for the feedback. The `convert` dependency is missing for `GRAFED`. You should be able to install it using 
``` bash
brew install imagemagick
```
See [this post](https://apple.stackexchange.com/questions/335635/where-is-the-convert-command-in-macos)

**Comment by Arvendui** [comment]
> Thank you for the feedback. The `convert` dependency is missing for `GRAFED`. You should be able to install it on MacOS using
> 
> ```shell
> brew install imagemagick
> ```
> 
> See [this post](https://apple.stackexchange.com/questions/335635/where-is-the-convert-command-in-macos)

It solved the issue

**Comment by docbrown1955** [comment]
Perfect, I close this issue then
