### ISSUE TITLE
gsl/gsl_complex_math.h: No such file or directory (MacOS)

### ISSUE THREAD

**Issue by Arvendui** [docbrown1955/marty-public#25]
new issue when running make install

**Comment by docbrown1955** [comment]
Did you install `gsl` ? 

If yes, this is a path issue. I had the same problem with `MacOS`. It seems that `homebrew` is installing libraries in `/usr/local` but sometimes this path is not included in system paths. Could you tell me the result of the following command ?
``` bash
echo $CPATH
echo $C_INCLUDE_PATH
```

**Comment by Arvendui** [comment]
> Did you install `gsl` ?
> 
> If yes, this is a path issue. I had the same problem with `MacOS`. It seems that `homebrew` is installing libraries in `/usr/local` but sometimes this path is not included in system paths. Could you tell me the result of the following command ?
> 
> ```shell
> echo $CPATH
> echo $C_INCLUDE_PATH
> ```

I have `gsl` installed. The two other commands output a blank line

**Comment by docbrown1955** [comment]
Ok then you should add this in your `${HOME}/.bashrc` file:
``` bash
    export PATH=$PATH:/usr/local/bin
    export CPATH=$CPATH:/usr/local/include
    export C_INCLUDE_PATH=$C_INCLUDE_PATH:/usr/local/include
    export LIBRARY_PATH=$LIBRARY_PATH:/usr/local/ib
    export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:/usr/local/lib
```
And reload your bash session either by opening a new terminal or executing 
``` bash
source ${HOME}/.bashrc
```

**Comment by Arvendui** [comment]
> So now you should have non empty `CPATH` and `C_INCLUDE_PATH` variables. Could you check ?
> 
> Also, could you check `gsl` is actually located in `/usr/local` ?
> 
> ```shell
> ls /usr/local/gsl/*
> ```

I does not find `gsl` in `usr/local`; running `ls /usr/local/bin/gsl*` yields `/usr/local/bin/gsl-config	/usr/local/bin/gsl-histogram	/usr/local/bin/gsl-randist	/usr/local/bin/gsleep		/usr/local/bin/gslj		/usr/local/bin/gslp`

The two paths are now both `:/usr/local/include`

**Comment by docbrown1955** [comment]
Could you try to locate `gsl` ?
For example 
``` bash
locate libgsl
```
Or try to reinstall it 
``` bash
brew install gsl
```
