### ISSUE TITLE
error.h: No such file or directory

### ISSUE THREAD

**Issue by Arvendui** [docbrown1955/marty-public#28]
when running `make` I get `../marty_bis/src/marty/core/wilsonOperator.cpp:17:10: fatal error: error.h: No such file or directory
   17 | #include "error.h"
      |          ^~~~~~~~~
compilation terminated.
make[2]: *** [src/marty/core/CMakeFiles/marty-core.dir/wilsonOperator.cpp.o] Error 1
make[1]: *** [src/marty/c`

note: I am using the setup discussed in [#22 ] and [#25 ]

**Comment by docbrown1955** [comment]
This seems to be an internal error to Qt. Which version do you have ? Apparently the 5.13 version introduced a mistake

**Comment by Arvendui** [comment]
> qmake --version

Using Qt version 5.9.7 in /opt/anaconda3/lib

**Comment by docbrown1955** [comment]
I have the very same version. Not sure I can help much on this..

Try to see if you can find out the origin, the issue surely does not come from `MARTY`

**Comment by Arvendui** [comment]
> I have the very same version. Not sure I can help much on this..
> 
> Try to see if you can find out the origin, the issue surely does not come from `MARTY`

I `brew install octave` and was able to install everything

**Comment by Arvendui** [comment]
> > Next issue is, how do I run the code: when I just do `g++ -std=c++17 -c main.cpp -o main.o` I get an error that makes me suspect that I am not using the "right" c++. Any suggestions?
> 
> In particular when I try to use ` /usr/local/bin/g++-11` which is the compiler I set for the `export` I get `marty.h: No such file or directory`

It works with `-I /usr/local/include/`

**Comment by docbrown1955** [comment]
Perfect, I close this issue
