### ISSUE TITLE
grafed-gui graphs.json >&/dev/null

### ISSUE THREAD

**Issue by Arvendui** [docbrown1955/marty-public#29]
When, following the tutorial I try to display the Feynman rules, `auto rules = toyModel.getFeynmanRules();Show(rules);`I get `grafed-gui graphs.json >&/dev/null`

**Comment by docbrown1955** [comment]
Could you tell me what happens when you launch
``` bash
grafed-gui graphs.json >/dev/null 2>&1 & sleep 1
```

`GRAFED` should launch and display no output in the terminal, And you should get back the command line after a second without closing the window.

If this works I will change the behavior (for now the command only works on Linux apparently, the one above should work also on MacOS)

**Comment by docbrown1955** [comment]
Do you have `grafed-gui` in the path ? `/usr/local/bin` should be in the `$PATH` variable

**Comment by Arvendui** [comment]
> > Could you tell me what happens when you launch
> > ```shell
> > grafed-gui graphs.json >/dev/null 2>&1 & sleep 1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > `GRAFED` should launch and display no output in the terminal, And you should get back the command line after a second without closing the window.
> > If this works I will change the behavior (for now the command only works on Linux apparently, the one above should work also on MacOS)
> 
> `[1] 78895 [1]+ Abort trap: 6 grafed-gui graphs.json > /dev/null 2>&1`



> Do you have `grafed-gui` in the path ? `/usr/local/bin` should be in the `$PATH` variable

I am a bit confused by what should I check....

**Comment by docbrown1955** [comment]
If you do 
``` bash
echo $PATH
```

**Comment by docbrown1955** [comment]
Otherwise you have to 
``` bash
export PATH=$PATH:/usr/local/bin
```
(and copy the line in your `${HOME}/.bashrc` file for all the next times

**Comment by Arvendui** [comment]
> If you do
> 
> ```shell
> echo $PATH
> ```
> 
> the `/usr/local/bin` should appear

I get `/opt/local/bin:/opt/local/sbin:/opt/anaconda3/bin:/opt/anaconda3/condabin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/Applications/anaconda3/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/Library/Apple/usr/bin` so it seems that I do?

**Comment by Arvendui** [comment]
> ```shell
> /usr/local/bin/grafed-gui graphs.json
> ```

there is, and when I run the command you suggested, I get `dyld[79130]: Library not loaded: @rpath/libQt5PrintSupport.5.dylib
  Referenced from: /usr/local/bin/grafed-gui
  Reason: tried: '/usr/local/lib/libQt5PrintSupport.5.dylib' (no such file), '/usr/lib/libQt5PrintSupport.5.dylib' (no such file)
Abort trap: 6`

**Comment by Arvendui** [comment]
> When you executed the example, did the program continued to run after `Show()` ?

Yes it does

**Comment by docbrown1955** [comment]
> > When you executed the example, did the program continued to run after `Show()` ?
> 
> Yes it does

Ok so at least it is not blocking, you just cannot see the graphs.

**Comment by Arvendui** [comment]
> DYLD_LIBRARY_PATH

`echo $DYLD_LIBRARY_PATH` does not return any path

**Comment by Arvendui** [comment]
> > > When you executed the example, did the program continued to run after `Show()` ?
> > 
> > 
> > Yes it does
> 
> Ok so at least it is not blocking, you just cannot see the graphs.

exactly

**Comment by docbrown1955** [comment]
Maybe you can see [this issue](https://stackoverflow.com/questions/45979459/qterror-library-not-loaded-rpath-libqt5printsupport-5-dylib) that addresses the same problem

**Comment by Arvendui** [comment]
running `locate libQt5PrintSupport` (which is the library it cannot find), returns paths `/opt/anaconda3/lib/libQt5PrintSupport.5.9.7.dylib`. How can I add this path?

**Comment by Arvendui** [comment]
`export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:/usr/local/anaconda3/lib/` got the job done
