### ISSUE TITLE
Possibility to view simplified readable output

### ISSUE THREAD

**Issue by amanmdesai** [docbrown1955/marty-public#60]
Hello,

This is regarding the output of MARTY after computing the amplitudes.

In the final result, there are abbreviations (implemented automatically by Marty). While this maybe useful when viewing results on terminal, it would be useful to know if there exists is a way to export the output to a latex with all the abbreviations substituted back into the final result (just the way it is in LanHEP).

Thanks,
Aman

**Comment by docbrown1955** [comment]
Hello Aman,
There is no built-in way to generate a LaTeX expression for now, although I am thinking to make it happen soon.

To expand abbreviations in a `csl::Expr` object, it is enough to call the following function:
``` c++
    csl::Evaluate(expr, csl::eval::abbreviation);
```
Also, from a `mty::Amplitude` object it is possible to get the list of expressions (one for each diagram) using:
``` cpp
    std::vector<csl::Expr> diagramExpressions = amplitude.obtainExpression();
```
Combining these two techniques you should be able to at least get the expanded output for all diagrams, even thoug it will not be directly a LaTeX expression.

**Comment by amanmdesai** [comment]
Hello @docbrown1955 

Thanks for your reply and suggestion. This should be helpful.

**Comment by docbrown1955** [comment]
See the related PR to support nice latex output ;)
https://github.com/docbrown1955/marty-public/pull/62
