### ISSUE TITLE
[Question] Regarding conversion of model to UFO for instance for further use with Madgraph

### ISSUE THREAD

**Issue by amanmdesai** [docbrown1955/marty-public#61]
How to convert a MARTY model to UFO format for instance for further use with Madgraph?

I see that there is submodule with UFO commands and wish to know how to use it.

Thanks,
Aman

**Comment by docbrown1955** [comment]
The module is a work in progress. For now, it only allows the caller to convert a `MARTY` model (or more specifically its Feynman rules) into a list of Vertex objects more suitable for a conversion to UFO.

To be more clear, the conversion to UFO is not provided but it is possible to get a list of `Vertex` objects which information is less general than in `MARTY` models, and correspond to UFO conventions instead (direct access to the electric charge, Lorentz factor, color factor etc).
