### ISSUE TITLE
error: invalid use of incomplete type 'class csl::Parent' [-fpermissive] in macOS

### ISSUE THREAD

**Issue by neerajanand321** [docbrown1955/marty-public#63]
![Screenshot 2023-06-28 at 12 37 57 PM](https://github.com/docbrown1955/marty-public/assets/78193865/478af900-bfc6-476a-90aa-5243135f71b8)

**Comment by neerajanand321** [comment]
I got this error after running the command "make" in build directory.

**Comment by docbrown1955** [comment]
Hello,
Could you give more details about the OS, compiler you are using ? Also, what sequence of commands ends up on this particular error ?

**Comment by docbrown1955** [comment]
I see you are using gcc-13, for which MARTY has not been tested yet. Could you try with an older gcc e.g. gcc-12 ?

**Comment by neerajanand321** [comment]
I tried to downgrade gcc using command 'brew install gcc@12'
but again getting the same error. I think the gcc version is still 13. Any idea how to downgrade it?

**Comment by neerajanand321** [comment]
I have solved the above issue and successfully installed it but when I run ctest, only 51 out of 99 got passed.

**Comment by docbrown1955** [comment]
Is Marty installed in a location accessible at runtime ? I think on Mac it is the DYLD_LIBRARY_PATH variable that has to be set (to the marty/install/lib directory) for the libraries to be found at runtime.

You can also lauch 
``` bash
    ctest --output-on-failure
```
To see the output of failed tests. Tell me how it goes 😊

**Comment by neerajanand321** [comment]
Upon running `ctest --output-on-failure` I am getting this error "include/libdiagonalization.h:7:10: fatal error: gsl/gsl_matrix.h: No such file or directory"

**Comment by docbrown1955** [comment]
I saw in your initial message that you have a "gsl/gsl_matrix.h" not found error. Is is still the case ? The error you finally reported is simply the consequence of the test not being able to run.

You should locate the GSL install, and add the appropriate environnement variables. Check for example in `usr/local`: if GSL is installed there, you should then add the following environnement variables:
``` bash
   CPATH="$CPATH;/usr/local/include"
   C_INCLUDE_PATH="$C_INCLUDE_PATH;/usr/local/include"
   DYLD_LIBRARY_PATH="$DYLD_LIBRARY_PATH;/usr/local/lib"
```

See [this thread](https://superuser.com/questions/894958/mac-os-x-xcode-libraries) for example. Tell me if you can find the appropriate paths.
