### ISSUE TITLE
Improved safety for param_t structures

### ISSUE THREAD

**Issue by marco-palmiotto** [docbrown1955/marty-public#69]
Hi, while I am finishing to improve the compare branch (to avoid the warnings), I noticed two important improvements that can be done for the `param_t` type and its use. In particular
1. calling `par->getName()` instead of `par->name` in the `print` function. This allows to set `name` as private in `InintSanitizer`
2. making `print` a `const` method, to allow for calling it in scopes where the `param_t` variable is qualified as `const`

I can do them myself in the `compare` branch, however I could not find the correct source files to modify them.

**Comment by docbrown1955** [comment]
I'm surprised for point 2., it should be const indeed! The function generating the `param_t` struct is in [src/csl/librarygroup.cpp](https://github.com/docbrown1955/marty-public/blob/708342f7e7eb9e47d3c79fdb3c06ee3adbd8a0b5/src/csl/librarygroup.cpp#L202) if you want to take a look ;)

For point 1., I do not see much difference between a public attribute and a private one with get/set methods. As the name in this case is not supposed to be anything else than a simple (string) data, a public attributes makes sense IMO.

**Comment by marco-palmiotto** [comment]
Thanks, I'll definitely look at point 2 then!

For point 1, I have been having some issues yesterday while writing the operators for the template in a way that does not override the name variable. So, the proposition of point 1 is due to three things:
1. Least privilege principle
2. If I change the typing of `name` (thing that I tried to do yesterday with an `unique_ptr` to avoid its copy), with `getName()` I can always be sure to return a `char *` or a `std::string`, which is surely going to work in the context of the overload of `<<`. 
3. Same goes for the method `setName()`, which becomes independent of the implementation of `name`.

Finally, I know that probably such an implementation will not change once I finish all my tests, but it can help having a more portable code IMO :)
